#!/bin/bash
#
# pre-commit-excel: have git handle xlsx files by deflating them and storing
#                   the XML in the repository, not the zip file. 
#
#                   companion to post-commit-excel
#

# -- config -- #
TMP_PREFIX='.~' # prefix XML directory--should NOT conflict with 
                   # anything in your repo

# -- end config -- #

echo
echo "=== Pre-commit PPTX processing ===="

unpack_pptx () {
    # unzip the pptx file 
    if [ -e "$1" ]; then
        if [ -e "${TMP_PREFIX}$1" ]; then rm -rf "${TMP_PREFIX}$1"; fi
        unzip "$1" -d "${TMP_PREFIX}$1"
    else
        # abort the commit if this isn't an excel file somehow
        echo "$1 is not an pptx file. this is a bug."
        exit 3
    fi
}

# create a placeholder text file for the .pptx file, which uniquely identifies
# it and prevents losing work on a checkout
replace_with_placeholder () {
    sha1sum "$1" | tee "$1" > /dev/null # hack for overwriting without temp file
}


reformat_xmls () {
    # reformat the xml file to many lines
    find "$1" -name "*.xml" -type f -exec xmllint --output '{}' --format '{}' \;
}

# check that the swap file isn't there (if the pptx has been staged)
for i in $(git diff --name-only --cached -- *.pptx); do 
    dir=$(dirname "$i")
    file=$(basename "$i")
    if [ -e "$dir/~\$$file" ]; then
        echo "$file swap file present: close pptx file before committing"
        exit 2 # excel file is open
    fi
done

# unpack all the zipfiles (if the pptx has been staged)
for i in $(git diff --name-only --cached -- *.pptx); do 
    dir=$(dirname "$i")
    file=$(basename "$i")
    cd "$dir"
    unpack_pptx "$file"
    replace_with_placeholder "$file"
    echo -n "Commit placeholder file: "
    file "$file"
    reformat_xmls "${TMP_PREFIX}$file"
    cd -

    # stage the XML files and the placeholder
    git add "$dir/${TMP_PREFIX}$file"
    git add "$dir/$file"
done

echo "=== End of pre-commit processing ==="
echo

